// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akiamiuviaghseismhdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFraWFtaXV2aWFnaHNlaXNtaGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDE1NTksImV4cCI6MjA3MTk3NzU1OX0.NknMOMs2BLksNUakVw8fwil5DjfIHdVPmifGmX0cJrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});